### ISSUE TITLE
Possibility of PyPI publication

### ISSUE THREAD

**Issue by jarjumarvin** [JSv4/Python-Redlines#8]
Dear Contributors

Would it be possible for you to switch to using PyPI to publish the library? We use a system for requirements that does not allow for   direct github requirements.

Thanks for any information.

**Comment by jarjumarvin** [comment]
Alternatively, currently the only viable requirement appears to be through `python_redlines @ git+https://github.com/JSv4/Python-Redlines@v0.0.1` as is suggested in the README. Would you be able to upgrade this to the latest release v0.0.4?

**Comment by JSv4** [comment]
@jarjumarvin, I took a stab at a pypi release, but it ended up being more complicated than desired due to being unable to host the binaries as part of the wheel (too big). I've been too busy, unfortunately, to build the infrastructure that would be necessary. If I could host the binaries on AWS or, better, a free host - and build and push them each time we do a new release - that's the route that would work. We basically need to do what spacy or transformers libraries do and download a binary after installation.

Welcome your assist with this. I have some time to assist but I'm pretty bandwidth constrained atm.

**Comment by JSv4** [comment]
I should add that I guess you could build the binaries on install via pypi, but that is super slow and I'm worried people using this as part of CI/CD would find this too slow. Maybe that's where we should start though? Make this available via pypi and you just have to build the engine on install for now...

**Comment by JSv4** [comment]
Closing for now. Open to PyPi publication but not hearing a ton of demand.
